export const surpriseMePrompts = [
    'Just Do It - Nike',
    'Think different - Apple',
    'A Diamond is Forever - De Beers',
    'When you care enough to send the very best - Hallmark',
    'I’d walk a mile for a Camel - Camel',
    'Quality never goes out of style - Levi’s',
    'Finger Lickin’ Good - KFC',
    'Shave Time. Shave Money. - Dollar Shave Club',
    'With a name like Smucker’s, it has to be good - Smucker’s',
    'Snap, Crackle and Pop! - Rice Krispies',
    'Open Happiness - Coca Cola',
    'So easy, a caveman can do it - Geico',
    '15 minutes can save you 15 percent or more on car insurance - Geico',
    'Belong anywhere - Airbnb',
    'The Relentless Pursuit of Perfection - Lexus',
    'The Ultimate Driving Machine - BMW',
    'The Quicker Picker Upper - Bounty',
    'The Happiest Place On Earth - Disneyland',
    'We Bring Good Things to Life - General Electric',
    'The King of Beers - Budweiser',
    'Fly the friendly skies - United Airlines',
    'Because You’re Worth It - L’oreal',
    'Think Small - Volkswagon',
    'We Are The Competition - Ferrari',
    'THINK - IBM campaign',
    'Confidence in Motion - Subaru',
    'Let’s Go Places- Toyota',
    'America Runs on Dunkin’ - Dunkin’ Donuts',
    'I’m Lovin’ It - McDonald’s',
    'Betcha can’t eat just one! - Lay’s',
    'When it rains, it pours- Morton, Salt',
    'Taste the Rainbow - Skittles',
    'Trix are for kids - Trix Cereal',
    'The Breakfast of Champions - Wheaties',
    'Melts in your mouth, not in your hand - M&M’s',
    'Eat Fresh - Subway',
    'Red Bull gives you wings - Red Bull',
    'Got Milk? - California Milk Processor Board',
    'Have It Your Way - Burger King',
    'Can you hear me now? - Verizon',
    'The Few, The Proud, The Marines - United States Marine Corps',
    'What Happens Here, Stays Here - Las Vegas',
    'When it absolutely, positively has to be there overnight - FedEx',
    'All the News That’s Fit to Print - The New York Times',
    'Strong enough for a man, but made for a woman - Secret',
    'The Citi Never Sleeps - Citibank',
    'Everywhere you want to be - Visa',
    'Maybe she’s born with it. Maybe it’s Maybelline. - Maybelline',
    'Hello Boys - Wonderbra',
    'We have a place for everyone - Vrbo',
    'The Best or Nothing - Mercedes-Benz',
    'Make every second count - TikTok',
    'There are some things money can’t buy. For everything else, there’s MasterCard. -MasterCard'
    
  ];
  